name: Build (WIN)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-2019
    steps:
      - name: set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: check out repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: install backend dependencies
        run: |
          cd EfficientIR
          pip install -r requirements.txt
      - name: build EfficientIR
        run: |
          cd EfficientIR
          pyinstaller build_nogui.spec
      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: install frontend dependencies
        run: |
          npm install -g yarn
          yarn
      - name: build DupimgFinder
        run: yarn build
      - name: release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.exe
            dist/*.zip
